# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/Project/Project.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/sources_1/ip/cordic_1/cordic_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_1 || ORIG_REF_NAME==cordic_1} -quiet] -quiet

# IP: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/sources_1/ip/cordic_2/cordic_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_2 || ORIG_REF_NAME==cordic_2} -quiet] -quiet

# IP: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# XDC: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/constrs_1/new/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/Project/Project.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/sources_1/ip/cordic_0/cordic_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/sources_1/ip/cordic_1/cordic_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_1 || ORIG_REF_NAME==cordic_1} -quiet] -quiet

# IP: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/sources_1/ip/cordic_2/cordic_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_2 || ORIG_REF_NAME==cordic_2} -quiet] -quiet

# IP: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# XDC: c:/Users/khanm/OneDrive/Users/khanm/OneDrive/Documents/GitHub/ECE532_Project_MVP/jacobi 1 1/jacobi 1/jacobi/jacobi.srcs/constrs_1/new/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
